### ISSUE TITLE
Include asciidoctor-diagram in bundle ant task

### ISSUE THREAD

**Issue by binout** [asciidoctor/asciidoctor-ant#62]
asciidoctor-ant wraps asciidoctorj-core (and asciidoctorj-pdf), but not asciidoctor-diagram ... You need to include it as an external gem (Cf. https://github.com/binout/asciidoctor-ant-examples#diagram).

Extracted from #53

**Comment by ctargett** [comment]
What was the reason why this wasn't in the 1.6.0-alpha.16 release that just came out? I'm struggling to get asciidoctor-diagram to work with asciidoctorj-pdf and having the dependency automatically included in asciidoctor-ant would maybe help (and would definitely help later so I don't have to mess with dependency issues on in our Jenkins jobs). We need the 1.6.0-alpha releases because they include other changes in asciidoctor-pdf that we need.

**Comment by binout** [comment]
No particular reason, just forget to report the feature on 1.6.x branch...sorry
Will be shipped with the next release 1.6.0-X
